services:
  # Générateur de configuration automatique
  config-generator:
    image: python:3.11-alpine
    volumes:
      - ./config:/app
    working_dir: /app
    env_file:
      - .env
      - path: .env.local
        required: false
    command: python generate_config.py

  # Traefik proxy
  traefik:
    image: traefik:v3.5
    ports:
      - "6080:80"
      - "5080:8080"
    volumes:
      - ./config/traefik.yml:/traefik.yml:ro
    restart: unless-stopped
    networks:
      - local_network
    depends_on:
      config-generator:
        condition: service_completed_successfully

  # cloudflare-tunnel:
  #   image: cloudflare/cloudflared
  #   command: tunnel run --config /etc/cloudflared/config.yml
  #   volumes:
  #     - ./config/cloudflared.yml:/etc/cloudflared/config.yml:ro
  #     - ~/.cloudflared:/root/.cloudflared:ro
  #   restart: unless-stopped
  #   networks:
  #     - local_network

networks:
  local_network:
    external: true
